apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
      - name: ingestion-api
        image: viniciusdelr/agrosolutions-ingestionservice:v1 
        ports:
        - containerPort: 8080
        env:
        - name: RabbitMQ__Host
          value: "rabbitmq-service" 
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ingestion